version: 2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
shallow_clone: true
build_script:
- cmd: dotnet publish --no-self-contained -c Release -r win-x64 -p:Version=%APPVEYOR_BUILD_VERSION%
on_success:
- ps: |
    [Environment]::CurrentDirectory = $PWD

    Add-Type -A System.IO.Compression.FileSystem

    $buildSuffix = [Environment]::GetEnvironmentVariable("appveyor_build_version")
    $zipFilename = "LogMeOn-$buildSuffix.zip"
    write-host "Zip filename: $zipFilename"

    [IO.Compression.ZipFile]::CreateFromDirectory('Builds\\Release-win-x64-publish', $zipFilename)

    Push-AppveyorArtifact $zipFilename
