version: 2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
shallow_clone: true
before_build:
- ps: |
    [Environment]::CurrentDirectory = $PWD
    $commitId = [Environment]::GetEnvironmentVariable("APPVEYOR_REPO_COMMIT").Substring(0,6)
    [System.IO.File]::WriteAllText("Src\Program.cs", [System.IO.File]::ReadAllText("Src\Program.cs").Replace("(000000)","($commitId)"))
build_script:
- cmd: dotnet publish --no-self-contained -c Release -r win-x64 -p:Version=%APPVEYOR_BUILD_VERSION%
on_success:
- ps: |
    [Environment]::CurrentDirectory = $PWD

    Add-Type -A System.IO.Compression.FileSystem

    $commitId = [Environment]::GetEnvironmentVariable("APPVEYOR_REPO_COMMIT").Substring(0,6)
    $buildSuffix = [Environment]::GetEnvironmentVariable("appveyor_build_version")
    $zipFilename = "LogMeOn-$buildSuffix-$commitId.zip"
    write-host "Zip filename: $zipFilename"

    [IO.Compression.ZipFile]::CreateFromDirectory('Builds\\Release-win-x64-publish', $zipFilename)

    Push-AppveyorArtifact $zipFilename
